AresDataProvider.Web/Controllers/DemoViewController.cs
using System;
using System.Globalization;
using System.Threading;
using System.Web.Mvc;

namespace AresDataProvider.Web.Controllers
{
	public class DemoViewController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		protected override void OnActionExecuting(ActionExecutingContext filterContext)
		{
			try
			{
				Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture((string)filterContext.RouteData.Values["lang"]);
				Thread.CurrentThread.CurrentUICulture = new CultureInfo((string)filterContext.RouteData.Values["lang"]);
			}
			catch(Exception) { }
		}
	}
}

AresDataProvider.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>KEEN|MATE - Ares Wrapper</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	@Styles.Render("~/Content/SemanticUI"))
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("KEEN|MATE - Ares wrapper", "Index", "DemoView", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>
						@Html.ActionLink("Česky", "Index", "DemoView", new { lang = "cs-CZ" }, null)
					</li>
					<li>
						@Html.ActionLink("English", "Index", "DemoView", new { lang = "en" }, null)
					</li>
				</ul>
			</div>
		</div>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/SemanticUI")
	<script src="https://unpkg.com/vue-router/dist/vue-router.js"></script>
	<script src="https://unpkg.com/vue"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.min.js"></script>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; @DateTime.Now.Year - KEEN|MATE Ares wrapper</p>
		</footer>
	</div>
	@Scripts.Render("~/bundles/bootstrap")
	@Scripts.Render("~/bundles/Vue")
	@RenderSection("scripts", required: false)
</body>
</html>